quarkus.datasource.db-kind=PostgreSQL
quarkus.datasource.username=pfm_user
quarkus.datasource.password=admin123

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pfm_db
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true



# Keycloak / OIDC
quarkus.oidc.auth-server-url=http://localhost:8180/realms/personal-finance-manager
quarkus.oidc.client-id=pfm-client
quarkus.oidc.credentials.secret=j84yCuLz11mtE1EBioTsRByns5fmxgBq
quarkus.oidc.application-type=service

# REST Clients
quarkus.rest-client.ip-api.url=https://api.ipify.org
quarkus.rest-client.timezone-api.url=https://timeapi.io
quarkus.rest-client.location-api.url=https://ipapi.co