quarkus.datasource.db-kind=PostgreSQL
quarkus.datasource.username=pfm_user
quarkus.datasource.password=admin123

quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pfm_db
quarkus.datasource.jdbc.max-size=16

quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true